### ISSUE TITLE
unable to reproduce benchmark

### ISSUE THREAD

**Issue by setop** [lucianmarin/logparser#1]
I tried on a 4M lines log file (840MB)

logparser gives me 20'926 line/s

goaccess gives me 67,189 line/s

So instead of having logparser being 4x faster, I have goaccess being 3.2x faster

What do I missed ?

**Comment by lucianmarin** [comment]
`zcat -f sitename.log.gz | goaccess` gives around 6k/s for 1.3 version (server CPU).

`gunzip -c sub.log.gz | goaccess` gives around 40k/s for 1.5 version (laptop CPU).

I updated the README.
